releases:
- name: redis
  namespace: webtor
  chart: pascaliske/redis
  version: 0.0.2
  values:
    - usePassword: false
    - cluster:
        enabled: false
    - master:
        persistence:
          enabled: false
- name: content-prober
  namespace: webtor
  chart: webtor/content-prober
  version: 0.1.1
  values:
    - image:
        tag: 0.1.2
- name: magnet2torrent
  namespace: webtor
  chart: webtor/magnet2torrent
  version: 0.1.1
  values:
    - image:
        tag: 0.1.1
- name: external-proxy
  namespace: webtor
  chart: webtor/external-proxy
  version: 0.1.1
  values:
    - image:
        tag: 0.1.1
- name: video-info
  namespace: webtor
  chart: webtor/video-info
  version: 0.1.4
  values:
    - image:
        tag: 0.1.4
- name: torrent-archiver
  namespace: webtor
  chart: webtor/torrent-archiver
  version: 0.1.3
  values:
    - image:
        tag: 0.1.3
- name: torrent-store
  namespace: webtor
  chart: webtor/torrent-store
  version: 0.1.3
  values:
    - image:
        tag: 0.1.2
    - redis:
        enabled: true
- name: srt2vtt
  namespace: webtor
  chart: webtor/srt2vtt
  version: 0.1.1
  values:
    - image:
        tag: 0.1.1
- name: job-cleaner
  namespace: webtor
  chart: webtor/job-cleaner
  version: 0.1.3
  values:
    - image:
        tag: 0.1.3
- name: torrent-http-proxy
  namespace: webtor
  chart: webtor/torrent-http-proxy
  version: 0.1.24
  missingFileHandler: Warn
  values:
    - clients.yaml
    - seeder:
        image: ghcr.io/ios-web-tools/torrent-web-seeder:0.1.2
    - transcoder:
        image: ghcr.io/ios-web-tools/content-transcoder:0.2.2
    - service:
        type: NodePort
    - image:
        tag: 0.1.2
