image:
  repository: ghcr.io/ios-web-tools/torrent-archiver
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  topologyKeys: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

update:
  maxUnavailable: 1