replicaCount: 1

image:
  repository: ghcr.io/ios-web-tools/magnet2torrent
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
