image:
  repository: ghcr.io/ios-web-tools/torrent-http-proxy
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

secret: ""

useBandwidthLimit: false

jobNodeAffinity:
  key: ""
  value: ""

promAddr: ""

update:
  maxUnavailable: 1

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

node:
  cpu:
    high: 0
    low: 0
  bandwidth:
    high: 0
    low: 0
  network:
    iface: "eth0"

redirect:
  enabled: ""
  prefix: "abra--"
  addressType: "ExternalIP"

clickHouse:
  dsn: ""
  batchSize: 1000
  replicated: false

seeder:
  image:
    repository: ghcr.io/ios-web-tools/torrent-web-seeder
    tag: latest
  grace: 600
  cpu:
    requests: ""
    limits: ""
  memory:
    requests: ""
    limits: ""
  nodeAffinity:
    key: ""
    value: ""
  requestAffinity: ""

mbTranscoder:
  cpu:
    requests: ""
    limits: ""
  memory:
    requests: ""
    limits: ""
  nodeAffinity:
    key: ""
    value: ""

transcoder:
  image:
    repository: ghcr.io/ios-web-tools/content-transcoder:latest
    tag: latest
  grace: 600
  cpu:
    requests: ""
    limits: ""
  memory:
    requests: ""
    limits: ""
  nodeAffinity:
    key: ""
    value: ""
  requestAffinity: ""

snapshot:
  enabled: false
  startThreshold: 0.5
  startFullDownloadThreshold: 0.75
  torrentSizeLimit: 10
  downloadRatio: 2.0

aws:
  accessKeyId: ""
  secretAccessKey: ""
  bucket: ""
  endpoint: ""
  region: ""
  bucketSpread: ""
  noSSL: ""

clients: {}

rbac:
  create: true

service:
  type: ClusterIP
  ports: 
    http: 80
    httpprom: 8082
    grpc: 50051
  topologyKeys: []

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts: []
  tls: []

ingressGRPC:
  enabled: false
  annotations: {}
  paths: []
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}